//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.22 at 07:46:31 PM WET 
//


package org.jabref.logic.importer.fileformat.mods;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for digitalOriginDefinition.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * &lt;pre&gt;
 * &amp;lt;simpleType name="digitalOriginDefinition"&amp;gt;
 *   &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 *     &amp;lt;enumeration value="born digital"/&amp;gt;
 *     &amp;lt;enumeration value="reformatted digital"/&amp;gt;
 *     &amp;lt;enumeration value="digitized microfilm"/&amp;gt;
 *     &amp;lt;enumeration value="digitized other analog"/&amp;gt;
 *   &amp;lt;/restriction&amp;gt;
 * &amp;lt;/simpleType&amp;gt;
 * &lt;/pre&gt;
 * 
 */
@XmlType(name = "digitalOriginDefinition", namespace = "http://www.loc.gov/mods/v3")
@XmlEnum
public enum DigitalOriginDefinition {

    @XmlEnumValue("born digital")
    BORN_DIGITAL("born digital"),
    @XmlEnumValue("reformatted digital")
    REFORMATTED_DIGITAL("reformatted digital"),
    @XmlEnumValue("digitized microfilm")
    DIGITIZED_MICROFILM("digitized microfilm"),
    @XmlEnumValue("digitized other analog")
    DIGITIZED_OTHER_ANALOG("digitized other analog");
    private final String value;

    DigitalOriginDefinition(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DigitalOriginDefinition fromValue(String v) {
        for (DigitalOriginDefinition c: DigitalOriginDefinition.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
