//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.22 at 07:46:31 PM WET 
//


package org.jabref.logic.importer.fileformat.endnote;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for anonymous complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element ref="{}full-title" minOccurs="0"/&amp;gt;
 *         &amp;lt;element ref="{}abbr-1" minOccurs="0"/&amp;gt;
 *         &amp;lt;element ref="{}abbr-2" minOccurs="0"/&amp;gt;
 *         &amp;lt;element ref="{}abbr-3" minOccurs="0"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fullTitle",
    "abbr1",
    "abbr2",
    "abbr3"
})
@XmlRootElement(name = "periodical")
public class Periodical {

    @XmlElement(name = "full-title")
    protected FullTitle fullTitle;
    @XmlElement(name = "abbr-1")
    protected Abbr1 abbr1;
    @XmlElement(name = "abbr-2")
    protected Abbr2 abbr2;
    @XmlElement(name = "abbr-3")
    protected Abbr3 abbr3;

    /**
     * Gets the value of the fullTitle property.
     * 
     * @return
     *     possible object is
     *     {@link FullTitle }
     *     
     */
    public FullTitle getFullTitle() {
        return fullTitle;
    }

    /**
     * Sets the value of the fullTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link FullTitle }
     *     
     */
    public void setFullTitle(FullTitle value) {
        this.fullTitle = value;
    }

    /**
     * Gets the value of the abbr1 property.
     * 
     * @return
     *     possible object is
     *     {@link Abbr1 }
     *     
     */
    public Abbr1 getAbbr1() {
        return abbr1;
    }

    /**
     * Sets the value of the abbr1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Abbr1 }
     *     
     */
    public void setAbbr1(Abbr1 value) {
        this.abbr1 = value;
    }

    /**
     * Gets the value of the abbr2 property.
     * 
     * @return
     *     possible object is
     *     {@link Abbr2 }
     *     
     */
    public Abbr2 getAbbr2() {
        return abbr2;
    }

    /**
     * Sets the value of the abbr2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Abbr2 }
     *     
     */
    public void setAbbr2(Abbr2 value) {
        this.abbr2 = value;
    }

    /**
     * Gets the value of the abbr3 property.
     * 
     * @return
     *     possible object is
     *     {@link Abbr3 }
     *     
     */
    public Abbr3 getAbbr3() {
        return abbr3;
    }

    /**
     * Sets the value of the abbr3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Abbr3 }
     *     
     */
    public void setAbbr3(Abbr3 value) {
        this.abbr3 = value;
    }

}
