//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.22 at 07:46:31 PM WET 
//


package org.jabref.logic.importer.fileformat.medline;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for art.id.type.int.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * &lt;pre&gt;
 * &amp;lt;simpleType name="art.id.type.int"&amp;gt;
 *   &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&amp;gt;
 *     &amp;lt;enumeration value="pubmed"/&amp;gt;
 *     &amp;lt;enumeration value="medline"/&amp;gt;
 *     &amp;lt;enumeration value="pmcid"/&amp;gt;
 *     &amp;lt;enumeration value="pmcbook"/&amp;gt;
 *     &amp;lt;enumeration value="bookaccession"/&amp;gt;
 *   &amp;lt;/restriction&amp;gt;
 * &amp;lt;/simpleType&amp;gt;
 * &lt;/pre&gt;
 * 
 */
@XmlType(name = "art.id.type.int")
@XmlEnum
public enum ArtIdTypeInt {

    @XmlEnumValue("pubmed")
    PUBMED("pubmed"),
    @XmlEnumValue("medline")
    MEDLINE("medline"),
    @XmlEnumValue("pmcid")
    PMCID("pmcid"),
    @XmlEnumValue("pmcbook")
    PMCBOOK("pmcbook"),
    @XmlEnumValue("bookaccession")
    BOOKACCESSION("bookaccession");
    private final String value;

    ArtIdTypeInt(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ArtIdTypeInt fromValue(String v) {
        for (ArtIdTypeInt c: ArtIdTypeInt.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
