//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.22 at 07:46:31 PM WET 
//


package org.jabref.logic.importer.fileformat.medline;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * &lt;p&gt;Java class for anonymous complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element ref="{}Journal"/&amp;gt;
 *         &amp;lt;element ref="{}ArticleTitle"/&amp;gt;
 *         &amp;lt;choice&amp;gt;
 *           &amp;lt;sequence&amp;gt;
 *             &amp;lt;element ref="{}Pagination"/&amp;gt;
 *             &amp;lt;element ref="{}ELocationID" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *           &amp;lt;/sequence&amp;gt;
 *           &amp;lt;element ref="{}ELocationID" maxOccurs="unbounded"/&amp;gt;
 *         &amp;lt;/choice&amp;gt;
 *         &amp;lt;element ref="{}Abstract" minOccurs="0"/&amp;gt;
 *         &amp;lt;element ref="{}AuthorList" minOccurs="0"/&amp;gt;
 *         &amp;lt;element ref="{}Language" maxOccurs="unbounded"/&amp;gt;
 *         &amp;lt;element ref="{}DataBankList" minOccurs="0"/&amp;gt;
 *         &amp;lt;element ref="{}GrantList" minOccurs="0"/&amp;gt;
 *         &amp;lt;element ref="{}PublicationTypeList"/&amp;gt;
 *         &amp;lt;element ref="{}VernacularTitle" minOccurs="0"/&amp;gt;
 *         &amp;lt;element ref="{}ArticleDate" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *       &amp;lt;attGroup ref="{}attlist.Article"/&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "Article")
public class Article {

    @XmlElementRefs({
        @XmlElementRef(name = "Journal", type = Journal.class, required = false),
        @XmlElementRef(name = "ArticleTitle", type = ArticleTitle.class, required = false),
        @XmlElementRef(name = "Pagination", type = Pagination.class, required = false),
        @XmlElementRef(name = "ELocationID", type = ELocationID.class, required = false),
        @XmlElementRef(name = "Abstract", type = Abstract.class, required = false),
        @XmlElementRef(name = "AuthorList", type = AuthorList.class, required = false),
        @XmlElementRef(name = "Language", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "DataBankList", type = DataBankList.class, required = false),
        @XmlElementRef(name = "GrantList", type = GrantList.class, required = false),
        @XmlElementRef(name = "PublicationTypeList", type = PublicationTypeList.class, required = false),
        @XmlElementRef(name = "VernacularTitle", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ArticleDate", type = ArticleDate.class, required = false)
    })
    protected List<java.lang.Object> content;
    @XmlAttribute(name = "PubModel", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String pubModel;

    /**
     * Gets the rest of the content model. 
     * 
     * &lt;p&gt;
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "ELocationID" is used by two different parts of a schema. See: 
     * line 185 of file:/home/ricardo/IdeaProjects/SE2122_57912_58403_58655_58751_57960/jabref/src/main/resources/xjc/medline/nlmmedlinecitationset_160101.xsd
     * line 183 of file:/home/ricardo/IdeaProjects/SE2122_57912_58403_58655_58751_57960/jabref/src/main/resources/xjc/medline/nlmmedlinecitationset_160101.xsd
     * &lt;p&gt;
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the content property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the content property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getContent().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link Journal }
     * {@link ArticleTitle }
     * {@link Pagination }
     * {@link ELocationID }
     * {@link Abstract }
     * {@link AuthorList }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link DataBankList }
     * {@link GrantList }
     * {@link PublicationTypeList }
     * {@link JAXBElement }{@code <}{@link Text }{@code >}
     * {@link ArticleDate }
     * 
     * 
     */
    public List<java.lang.Object> getContent() {
        if (content == null) {
            content = new ArrayList<java.lang.Object>();
        }
        return this.content;
    }

    /**
     * Gets the value of the pubModel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPubModel() {
        return pubModel;
    }

    /**
     * Sets the value of the pubModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPubModel(String value) {
        this.pubModel = value;
    }

}
