//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.22 at 07:46:31 PM WET 
//


package org.jabref.logic.importer.fileformat.medline;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for iso.language.codes.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * &lt;pre&gt;
 * &amp;lt;simpleType name="iso.language.codes"&amp;gt;
 *   &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&amp;gt;
 *     &amp;lt;enumeration value="AF"/&amp;gt;
 *     &amp;lt;enumeration value="AR"/&amp;gt;
 *     &amp;lt;enumeration value="AZ"/&amp;gt;
 *     &amp;lt;enumeration value="BG"/&amp;gt;
 *     &amp;lt;enumeration value="CS"/&amp;gt;
 *     &amp;lt;enumeration value="DA"/&amp;gt;
 *     &amp;lt;enumeration value="DE"/&amp;gt;
 *     &amp;lt;enumeration value="EN"/&amp;gt;
 *     &amp;lt;enumeration value="EL"/&amp;gt;
 *     &amp;lt;enumeration value="ES"/&amp;gt;
 *     &amp;lt;enumeration value="FA"/&amp;gt;
 *     &amp;lt;enumeration value="FI"/&amp;gt;
 *     &amp;lt;enumeration value="FR"/&amp;gt;
 *     &amp;lt;enumeration value="HE"/&amp;gt;
 *     &amp;lt;enumeration value="HU"/&amp;gt;
 *     &amp;lt;enumeration value="HY"/&amp;gt;
 *     &amp;lt;enumeration value="IN"/&amp;gt;
 *     &amp;lt;enumeration value="IS"/&amp;gt;
 *     &amp;lt;enumeration value="IT"/&amp;gt;
 *     &amp;lt;enumeration value="IW"/&amp;gt;
 *     &amp;lt;enumeration value="JA"/&amp;gt;
 *     &amp;lt;enumeration value="KA"/&amp;gt;
 *     &amp;lt;enumeration value="KO"/&amp;gt;
 *     &amp;lt;enumeration value="LT"/&amp;gt;
 *     &amp;lt;enumeration value="MK"/&amp;gt;
 *     &amp;lt;enumeration value="ML"/&amp;gt;
 *     &amp;lt;enumeration value="NL"/&amp;gt;
 *     &amp;lt;enumeration value="NO"/&amp;gt;
 *     &amp;lt;enumeration value="PL"/&amp;gt;
 *     &amp;lt;enumeration value="PT"/&amp;gt;
 *     &amp;lt;enumeration value="PS"/&amp;gt;
 *     &amp;lt;enumeration value="RO"/&amp;gt;
 *     &amp;lt;enumeration value="RU"/&amp;gt;
 *     &amp;lt;enumeration value="SL"/&amp;gt;
 *     &amp;lt;enumeration value="SK"/&amp;gt;
 *     &amp;lt;enumeration value="SQ"/&amp;gt;
 *     &amp;lt;enumeration value="SR"/&amp;gt;
 *     &amp;lt;enumeration value="SV"/&amp;gt;
 *     &amp;lt;enumeration value="SW"/&amp;gt;
 *     &amp;lt;enumeration value="TH"/&amp;gt;
 *     &amp;lt;enumeration value="TR"/&amp;gt;
 *     &amp;lt;enumeration value="UK"/&amp;gt;
 *     &amp;lt;enumeration value="VI"/&amp;gt;
 *     &amp;lt;enumeration value="ZH"/&amp;gt;
 *   &amp;lt;/restriction&amp;gt;
 * &amp;lt;/simpleType&amp;gt;
 * &lt;/pre&gt;
 * 
 */
@XmlType(name = "iso.language.codes")
@XmlEnum
public enum IsoLanguageCodes {

    AF,
    AR,
    AZ,
    BG,
    CS,
    DA,
    DE,
    EN,
    EL,
    ES,
    FA,
    FI,
    FR,
    HE,
    HU,
    HY,
    IN,
    IS,
    IT,
    IW,
    JA,
    KA,
    KO,
    LT,
    MK,
    ML,
    NL,
    NO,
    PL,
    PT,
    PS,
    RO,
    RU,
    SL,
    SK,
    SQ,
    SR,
    SV,
    SW,
    TH,
    TR,
    UK,
    VI,
    ZH;

    public String value() {
        return name();
    }

    public static IsoLanguageCodes fromValue(String v) {
        return valueOf(v);
    }

}
