//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.22 at 07:46:31 PM WET 
//


package org.jabref.logic.importer.fileformat.medline;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for pub.status.int.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * &lt;pre&gt;
 * &amp;lt;simpleType name="pub.status.int"&amp;gt;
 *   &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&amp;gt;
 *     &amp;lt;enumeration value="pmc"/&amp;gt;
 *     &amp;lt;enumeration value="pmcr"/&amp;gt;
 *     &amp;lt;enumeration value="pubmed"/&amp;gt;
 *     &amp;lt;enumeration value="pubmedr"/&amp;gt;
 *     &amp;lt;enumeration value="premedline"/&amp;gt;
 *     &amp;lt;enumeration value="medline"/&amp;gt;
 *     &amp;lt;enumeration value="medliner"/&amp;gt;
 *     &amp;lt;enumeration value="entrez"/&amp;gt;
 *     &amp;lt;enumeration value="pmc-release"/&amp;gt;
 *   &amp;lt;/restriction&amp;gt;
 * &amp;lt;/simpleType&amp;gt;
 * &lt;/pre&gt;
 * 
 */
@XmlType(name = "pub.status.int")
@XmlEnum
public enum PubStatusInt {

    @XmlEnumValue("pmc")
    PMC("pmc"),
    @XmlEnumValue("pmcr")
    PMCR("pmcr"),
    @XmlEnumValue("pubmed")
    PUBMED("pubmed"),
    @XmlEnumValue("pubmedr")
    PUBMEDR("pubmedr"),
    @XmlEnumValue("premedline")
    PREMEDLINE("premedline"),
    @XmlEnumValue("medline")
    MEDLINE("medline"),
    @XmlEnumValue("medliner")
    MEDLINER("medliner"),
    @XmlEnumValue("entrez")
    ENTREZ("entrez"),
    @XmlEnumValue("pmc-release")
    PMC_RELEASE("pmc-release");
    private final String value;

    PubStatusInt(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PubStatusInt fromValue(String v) {
        for (PubStatusInt c: PubStatusInt.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
