//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.22 at 07:46:30 PM WET 
//


package org.jabref.logic.importer.fileformat.bibtexml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * &lt;p&gt;Java class for anonymous complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;choice&amp;gt;
 *           &amp;lt;element ref="{http://bibtexml.sf.net/}article"/&amp;gt;
 *           &amp;lt;element ref="{http://bibtexml.sf.net/}book"/&amp;gt;
 *           &amp;lt;element ref="{http://bibtexml.sf.net/}booklet"/&amp;gt;
 *           &amp;lt;element ref="{http://bibtexml.sf.net/}manual"/&amp;gt;
 *           &amp;lt;element ref="{http://bibtexml.sf.net/}techreport"/&amp;gt;
 *           &amp;lt;element ref="{http://bibtexml.sf.net/}mastersthesis"/&amp;gt;
 *           &amp;lt;element ref="{http://bibtexml.sf.net/}phdthesis"/&amp;gt;
 *           &amp;lt;element ref="{http://bibtexml.sf.net/}inbook"/&amp;gt;
 *           &amp;lt;element ref="{http://bibtexml.sf.net/}incollection"/&amp;gt;
 *           &amp;lt;element ref="{http://bibtexml.sf.net/}proceedings"/&amp;gt;
 *           &amp;lt;element ref="{http://bibtexml.sf.net/}inproceedings"/&amp;gt;
 *           &amp;lt;element ref="{http://bibtexml.sf.net/}conference"/&amp;gt;
 *           &amp;lt;element ref="{http://bibtexml.sf.net/}unpublished"/&amp;gt;
 *           &amp;lt;element ref="{http://bibtexml.sf.net/}misc"/&amp;gt;
 *         &amp;lt;/choice&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *       &amp;lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" /&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "article",
    "book",
    "booklet",
    "manual",
    "techreport",
    "mastersthesis",
    "phdthesis",
    "inbook",
    "incollection",
    "proceedings",
    "inproceedings",
    "conference",
    "unpublished",
    "misc"
})
@XmlRootElement(name = "entry")
public class Entry {

    protected Article article;
    protected Book book;
    protected Booklet booklet;
    protected Manual manual;
    protected Techreport techreport;
    protected Mastersthesis mastersthesis;
    protected Phdthesis phdthesis;
    protected Inbook inbook;
    protected Incollection incollection;
    protected Proceedings proceedings;
    protected Inproceedings inproceedings;
    protected Conference conference;
    protected Unpublished unpublished;
    protected Misc misc;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the article property.
     * 
     * @return
     *     possible object is
     *     {@link Article }
     *     
     */
    public Article getArticle() {
        return article;
    }

    /**
     * Sets the value of the article property.
     * 
     * @param value
     *     allowed object is
     *     {@link Article }
     *     
     */
    public void setArticle(Article value) {
        this.article = value;
    }

    /**
     * Gets the value of the book property.
     * 
     * @return
     *     possible object is
     *     {@link Book }
     *     
     */
    public Book getBook() {
        return book;
    }

    /**
     * Sets the value of the book property.
     * 
     * @param value
     *     allowed object is
     *     {@link Book }
     *     
     */
    public void setBook(Book value) {
        this.book = value;
    }

    /**
     * Gets the value of the booklet property.
     * 
     * @return
     *     possible object is
     *     {@link Booklet }
     *     
     */
    public Booklet getBooklet() {
        return booklet;
    }

    /**
     * Sets the value of the booklet property.
     * 
     * @param value
     *     allowed object is
     *     {@link Booklet }
     *     
     */
    public void setBooklet(Booklet value) {
        this.booklet = value;
    }

    /**
     * Gets the value of the manual property.
     * 
     * @return
     *     possible object is
     *     {@link Manual }
     *     
     */
    public Manual getManual() {
        return manual;
    }

    /**
     * Sets the value of the manual property.
     * 
     * @param value
     *     allowed object is
     *     {@link Manual }
     *     
     */
    public void setManual(Manual value) {
        this.manual = value;
    }

    /**
     * Gets the value of the techreport property.
     * 
     * @return
     *     possible object is
     *     {@link Techreport }
     *     
     */
    public Techreport getTechreport() {
        return techreport;
    }

    /**
     * Sets the value of the techreport property.
     * 
     * @param value
     *     allowed object is
     *     {@link Techreport }
     *     
     */
    public void setTechreport(Techreport value) {
        this.techreport = value;
    }

    /**
     * Gets the value of the mastersthesis property.
     * 
     * @return
     *     possible object is
     *     {@link Mastersthesis }
     *     
     */
    public Mastersthesis getMastersthesis() {
        return mastersthesis;
    }

    /**
     * Sets the value of the mastersthesis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mastersthesis }
     *     
     */
    public void setMastersthesis(Mastersthesis value) {
        this.mastersthesis = value;
    }

    /**
     * Gets the value of the phdthesis property.
     * 
     * @return
     *     possible object is
     *     {@link Phdthesis }
     *     
     */
    public Phdthesis getPhdthesis() {
        return phdthesis;
    }

    /**
     * Sets the value of the phdthesis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Phdthesis }
     *     
     */
    public void setPhdthesis(Phdthesis value) {
        this.phdthesis = value;
    }

    /**
     * Gets the value of the inbook property.
     * 
     * @return
     *     possible object is
     *     {@link Inbook }
     *     
     */
    public Inbook getInbook() {
        return inbook;
    }

    /**
     * Sets the value of the inbook property.
     * 
     * @param value
     *     allowed object is
     *     {@link Inbook }
     *     
     */
    public void setInbook(Inbook value) {
        this.inbook = value;
    }

    /**
     * Gets the value of the incollection property.
     * 
     * @return
     *     possible object is
     *     {@link Incollection }
     *     
     */
    public Incollection getIncollection() {
        return incollection;
    }

    /**
     * Sets the value of the incollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link Incollection }
     *     
     */
    public void setIncollection(Incollection value) {
        this.incollection = value;
    }

    /**
     * Gets the value of the proceedings property.
     * 
     * @return
     *     possible object is
     *     {@link Proceedings }
     *     
     */
    public Proceedings getProceedings() {
        return proceedings;
    }

    /**
     * Sets the value of the proceedings property.
     * 
     * @param value
     *     allowed object is
     *     {@link Proceedings }
     *     
     */
    public void setProceedings(Proceedings value) {
        this.proceedings = value;
    }

    /**
     * Gets the value of the inproceedings property.
     * 
     * @return
     *     possible object is
     *     {@link Inproceedings }
     *     
     */
    public Inproceedings getInproceedings() {
        return inproceedings;
    }

    /**
     * Sets the value of the inproceedings property.
     * 
     * @param value
     *     allowed object is
     *     {@link Inproceedings }
     *     
     */
    public void setInproceedings(Inproceedings value) {
        this.inproceedings = value;
    }

    /**
     * Gets the value of the conference property.
     * 
     * @return
     *     possible object is
     *     {@link Conference }
     *     
     */
    public Conference getConference() {
        return conference;
    }

    /**
     * Sets the value of the conference property.
     * 
     * @param value
     *     allowed object is
     *     {@link Conference }
     *     
     */
    public void setConference(Conference value) {
        this.conference = value;
    }

    /**
     * Gets the value of the unpublished property.
     * 
     * @return
     *     possible object is
     *     {@link Unpublished }
     *     
     */
    public Unpublished getUnpublished() {
        return unpublished;
    }

    /**
     * Sets the value of the unpublished property.
     * 
     * @param value
     *     allowed object is
     *     {@link Unpublished }
     *     
     */
    public void setUnpublished(Unpublished value) {
        this.unpublished = value;
    }

    /**
     * Gets the value of the misc property.
     * 
     * @return
     *     possible object is
     *     {@link Misc }
     *     
     */
    public Misc getMisc() {
        return misc;
    }

    /**
     * Sets the value of the misc property.
     * 
     * @param value
     *     allowed object is
     *     {@link Misc }
     *     
     */
    public void setMisc(Misc value) {
        this.misc = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
